1.Write a program to create a 5 dimensional array with all zeros and ones

In [3]:
import numpy as np

In [19]:
x = np.zeros((4,4),dtype=int)

In [22]:
x1 = np.array(x,ndmin=5)

In [23]:
x1

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]]]])

In [24]:
y = np.ones((5,5),dtype=int)

In [25]:
y1 = np.array(y,ndmin=5)

In [26]:
y1

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])

2.Write a python program to create an array of 10 zeros,10 ones,10 fives in row 1,2 and 3 which create a new array of shape (3,10)

In [59]:
zeros_array = np.zeros(10,dtype=int)
ones_array = np.ones(10,dtype=int)
fives_array = np.ones(10,dtype=int) * 5

result_array = np.array((zeros_array, ones_array, fives_array)).reshape(3,10)

print(result_array)


Resulting Array:
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5 5]]


In [62]:
x = np.array((np.zeros(10,dtype=int),np.ones(10,dtype=int),np.ones(10,dtype=int)*5)).reshape(3,10)

In [63]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

3.write a program to create a 3x4 matrix filled with values from 10 and 21.

In [84]:
arr1 = np.arange(10,22).reshape(3,4)

In [85]:
arr1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

4.Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9

In [86]:
diag_arr = np.diag([0,1,2,3,4,5,6,7,8,9])

In [87]:
diag_arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

5.Write a program to create 4x4 array .Create an array from array by swapping first and last , second and third coloumns

In [4]:
x = np.arange(1,17).reshape(4,4)

In [5]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:

coloumn1 = x[:, 0].copy()
x[:, 0] = x[:, 3]
x[:, 3] = coloumn1
coloumn2 = x[:,1].copy()
x[:,1] = x[:,2]
x[:,2] = coloumn2
print (x)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


6.Write a program to reverse an array first element should be last and last element should be first

In [21]:
r = np.arange(1,17)

In [22]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [23]:
r[::-1]

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

7.Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100


In [24]:
a = np.arange(1,101).reshape(10,10)

In [25]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [42]:
filtered_array = a[(a>30)&(a<80)&(a%5==0)]

In [44]:
filtered_array
# elements greater than 30 and less than 80 and multiples of 5

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

8.Write a program to create a 2D array with 1 on the border and 0 inside.


In [51]:
array = np.zeros((5,5),dtype=int)

In [52]:
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [53]:
array[0,:]=1
array[-1,:]=1
array[:,0]=1
array[:,-1]=1

In [54]:
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

9. Write a program to create a checkerboard pattern .Don't use default array function
   Checkerboard pattern:  


10. Write a program to find common values between two arrays.
    Expected Output:
    array1: [10 20 40 60]
    array2: [10, 30, 40,50]


In [66]:
array1 = [10,20,30,40,50]
array2 = [10,20,60,50]
rows=[]
cols=[]
for x in array1:
    if x in array2:
        rows.append(x)
    else:
        cols.append(x)
print(rows)        


[10, 20, 50]


11.Write a program to create an array 2d array and then reshape into 1d array


In [69]:
x2 = np.arange(1,10).reshape(3,3)

In [70]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.ndim(x2)

2

In [77]:
x3=x2.flatten()

In [78]:
x3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

12.Write a user defined function for creating a 1 or 2d array from scratch without using array functions
