# Data set - 1

In [2]:
import numpy as np

In [7]:
x = np.genfromtxt(r"C:\Users\srava\Downloads\train_extended.csv",delimiter=',',skip_header=1)

In [53]:
x

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

## 1.What is the minimum and maximum length

In [54]:
min_len = np.min(x[:,0])
max_len = np.max(x[:,0])
print('min_len = {}'.format(min_len))
print('max_len = {}'.format(max_len))

min_len = 0.0
max_len = 7.58349125


## 2.Difference between maximum and minimum length.

In [55]:
def diff_max_min(x):
    return (np.max(x))-(np.min(x))

In [59]:
y = np.apply_along_axis(diff_max_min,0,x)

In [60]:
y

array([ 7.58349125,  2.25      ,  2.825     , 80.07316275, 45.25997675,
       26.1098895 , 36.9960975 , 28.        ])

In [61]:
y[0]
#This is the length column

7.58349125

## 3.Find column wise average

In [62]:
def avg(x):
    return np.mean(x)

In [63]:
np.apply_along_axis(avg,0,x)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

## 4.Find out all the ages whose height is greater than 0.4

In [64]:
height = x[x[:,2]>0.4]

In [66]:
len(height)

55336

In [74]:
def total_ages(heights,ages):
    heights = x[:,2]
    ages = x[:,7]
    ages_fltrd = ages[heights>0.4]
    return ages_fltrd

In [76]:
total_ages(x,y)

array([11., 14., 13., ..., 11., 11., 11.])

## 5.What is the average height and weight of the persons whose age is greater than 10 ?

In [106]:

heights = x[:,2]
weights = x[:,3]
ages=x[:,7]
avg_heights = np.mean(heights[ages==10])
avg_weights= np.mean(weights[ages==10])
    
print('average heights whose age is = 10 : {}'.format(avg_heights))
print('average weights whose age is = 10 : {}'.format(avg_weights))

average heights whose age is = 10 : 0.3833672856539947
average weights whose age is = 10 : 28.243308450511314


## 6.What is the total shell weight ? 

In [118]:
total_shell_weight = np.sum(x[:,6])

In [119]:
total_shell_weight

1326845.8295214002

## 7.How many persons belong to each and every unique age ?

In [122]:
np.unique(x[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

## 8.What is the difference between shucked weight and viceversa weight ?

In [125]:
diff_btwn = x[:,4]-x[:,5]

In [126]:
diff_btwn

array([5.9817445, 3.855532 , 4.1106775, ..., 2.9199985, 5.329706 ,
       9.8372765])

## 9.What is average height of the persons whose age is between 14 and 19

In [136]:
height = x[:,2]
age = x[:,7]
filtered_ages = (age>=14)&(age<=19)
np.mean(height[filtered_ages])


0.41489902051107985

## 10.What is the average weight if we include shucked weight and viscera weight and shell weight ?

In [140]:
average_weight = x[:,4]+x[:,5]+x[:,6]
print("average_weight = ",np.mean(average_weight)) 

average_weight =  21.616780352404746


# Data set - 2

In [143]:
print("0 = index , 1 = total_bill , 2 = tip , 3 = sex , 4 = smoker , 5 = day , 6 = time , 7 = size")
y = np.genfromtxt(r"C:\Users\srava\Downloads\tipsf (1).csv",delimiter=',',skip_header=1)

0 = index , 1 = total_bill , 2 = tip , 3 = sex , 4 = smoker , 5 = day , 6 = time , 7 = size


In [144]:
y

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

## 1.What is the total bill value ?

In [146]:
total_bill = np.sum(y[:,1])

In [147]:
total_bill

4827.77

## 2.What is the total tip value ?

In [148]:
total_tip = np.sum(y[:,2])

In [149]:
total_tip

731.5799999999999

## 3.Count how many sunday,saturday,thursdays,fridays are there

In [150]:
np.unique(y[:,5],return_counts=True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

## 4.How many smokers are there

In [175]:
# smokers == 0
# non_smokers == 1
def smokers(y):
    smokers_count=0
    non_smokers_count =0
    for x in y[:,4]:
        if x==1:
            smokers_count+=1
        else:
            non_smokers_count+=1
    return smokers_count
           
    

In [176]:
smokers(y)

93

## 5.What is the avg tip given by male and female ?

In [202]:
# male = 1
# female = 0

male = y[y[:,3]==1]
female = y[y[:,3]==0]
print('Average_tip_of_male = ',np.mean(male[:,2]))
print('Average_tip_of_female = ',np.mean(female[:,2]))
        

Average_tip_of_male =  3.0896178343949043
Average_tip_of_female =  2.8334482758620685


## 6.How much amount have been spent by male and female?

In [203]:
print("Amount spent by male = ",np.sum(male[:,1]))
print("Amount spent by female = ",np.sum(female[:,1]))

Amount spent by male =  3256.8199999999997
Amount spent by female =  1570.9499999999996


## 7.What is the min and max tip given ?

In [206]:
max_tip = np.max(y[:,2])
min_tip = np.min(y[:,2])
print('Maximum tip = ',max_tip)
print('Minimum tip = ',min_tip)

Maximum tip =  10.0
Minimum tip =  1.0


## 8.How many male and females are going for lunch and dinner

## 9.Find out the avg size

In [207]:
avg_size = np.mean(y[:,7])
print('Average size = ',avg_size)

Average size =  2.569672131147541


## 10.How many female smokers are there and males are there ?

In [238]:
male_smokers = len(male[male[:,4]==1])
Female_smokers = len(female[female[:,4]==1])

In [236]:
print('Male_smokers = ',male_smokers)
print('Female_smokers = ',Female_smokers)

Male_smokers =  60
Female_smokers =  33
